### ISSUE TITLE
请问内容运营的职位还开放吗？

### ISSUE THREAD

**Issue by ithinco** [xitu/recruitment#1]
在微博上发的招聘中有这个职位，但是在拉勾上的招聘职位中却没有内容运营这个职位。如果还开放的话，能不能请 HR 在拉勾上开放这个职位呢？好方便投简历，谢谢。

**Comment by Glowin** [comment]
开放，欢迎投放运营岗位的简历，我们招聘邮箱是 hr@xitu.io，期待你的来信。
