### ISSUE TITLE
掘金团队一妹子很不错~   特发 issue

### ISSUE THREAD

**Issue by raisezhang** [xitu/recruitment#2]
![3](https://cloud.githubusercontent.com/assets/1481983/19774561/1e11e462-9ca0-11e6-98fc-5a55f99b0346.jpg)

酒窝很赞~  

![image](https://cloud.githubusercontent.com/assets/1481983/19774573/26310132-9ca0-11e6-8249-38fbc2a9daff.png)

**Comment by Kulbear** [comment]
🐑三的迷弟出现了～

**Comment by shliujing** [comment]
12寸mac？好小...

**Comment by gfwfail** [comment]
椅子不错啊
